---
title       : Math Test
subtitle    : For Developing Data Product course Assignment
author      : Li Xin
job         : Easy - Hard
logo        : Doraemon.png
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [bootstrap, quiz]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Introduction

This Math Test slidify is created for Developing Data Product course assignment. Multiple selection questions were designed in each page of slide from page 3. In each questions only has 1 correct answer. Press right arrow key to turn to next page after answer in chosen.

---&radio
## Question 1

1 + 1 = ?

1. 1
2. _2_
3. 3
4. 4

*** .hint
Need hint??

*** .explanation
Need explanation??


---&radio
## Question 2

If you choose an answer to this question at random, what's the change you will be correct?

1. 25%
2. 50%
3. 0%
4. 25%

*** .hint
No hint

*** .explanation
No answer to this question. sorry

---&radio
## Question 3

The statement "If x is divisible by 8, then it is divisible by 6" is false if x equals

1. 6
2. 14
3. _32_
4. 48

The slide ends here. Thank you!

*** .hint
Still no hint here. Please click "explanation" to get detailed explanation.

*** .explanation
A sentence in "If....then..." form is called an implication. The only time when an implication is false is when the "If" part of the sentence is true and the "then" part of the sentence is false. The number 32 makes the first part of the statement true and the second part of the statement false.
